apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sazurev1tsgverification
  annotations:
    metadata.gatekeeper.sh/title: "TSG verification"
    metadata.gatekeeper.sh/version: 1.0.0
    metadata.gatekeeper.sh/requires-external-data-source: tsg-provider
spec:
  crd:
    spec:
      names:
        kind: K8sAzureV1TSGVerification
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sazurev1tsgverification

        # Only validate platform.afo-nc.microsoft.com resources
        is_target {
            input.review.kind.group == "platform.afo-nc.microsoft.com"
        }

        # Get data from TSG external data source
        remote_data := response{
            is_target
            request_json_string := json.marshal(input.review)
            response := external_data({"provider": "tsg-provider", "keys": [request_json_string]})
        }

        # Base Gatekeeper violation
        violation[{"msg": msg}] {
            is_target
            general_violation[{"result": msg}]
        }

        # Check if there are any errors calling ed provider
        general_violation[{"result": result}] {
            remote_data.system_error != ""
            result := sprintf("System error calling external data provider: %s", [remote_data.system_error])
        }

        # Check if there are errors during validation
        general_violation[{"result": result}] {
            remote_data.system_error == ""
            count(remote_data.errors) > 0
            result := sprintf("Error validating approved CR content: %s", [remote_data.errors])
        }